pipeline {
    agent any

    environment {
        IMAGE_NAME     = "bookstore-app"
        CONTAINER_NAME = "bookstore-app"
        APP_PORT       = "2008"
    }

    stages {

        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                sh '''
                echo "Workspace: $WORKSPACE"
                ls -la

                echo "Building project inside Maven container..."

                docker run --rm \
                  -v "$WORKSPACE":/app \
                  -v /var/jenkins_home/.m2:/root/.m2 \
                  -w /app \
                  maven:3.9.6-eclipse-temurin-21 \
                  mvn clean package
                '''
            }
        }

        stage('Docker Build') {
            steps {
                sh '''
                echo "Building application Docker image..."
                cd "$WORKSPACE"
                docker build --pull -t $IMAGE_NAME .
                '''
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                echo "Deploying application..."

                docker network create bookstore-network || true

                docker rm -f $CONTAINER_NAME || true

                docker run -d \
                  --name $CONTAINER_NAME \
                  --network bookstore-network \
                  -p ${APP_PORT}:8080 \
                  -e SPRING_PROFILES_ACTIVE=docker \
                  $IMAGE_NAME

                echo "Deployment complete"
                '''
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
