pipeline {
    agent any

    environment {
        IMAGE_NAME = "bookstore-app"
        CONTAINER_NAME = "bookstore-app"
        APP_PORT = "2008"
        PROJECT_DIR = "bookStore"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                sh '''
                cd $PROJECT_DIR

                docker run --rm \
                  -v "$PWD":/app \
                  -v "$HOME/.m2":/root/.m2 \
                  -w /app \
                  maven:3.9.6-eclipse-temurin-21 \
                  mvn clean package
                '''
            }
        }

        stage('Docker Build') {
            steps {
                sh '''
                cd $PROJECT_DIR
                docker build -t $IMAGE_NAME .
                '''
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                docker rm -f $CONTAINER_NAME || true

                docker run -d \
                  --name $CONTAINER_NAME \
                  -p $APP_PORT:$APP_PORT \
                  $IMAGE_NAME
                '''
            }
        }
    }
}
